export const GET_DATA_FOR_PRODUCT_SUCCESSS = "productReducer/GET_DATA_FOR_EDIT_PRODUCT_SUCCESSS";
export const GET_DATA_FOR_PRODUCT_REQUEST = "productReducer/GET_DATA_FOR_EDIT_PRODUCT_REQUEST";
export const GET_DATA_FOR_PRODUCT_FAIL = "productReducer/GET_DATA_FOR_EDIT_PRODUCT_FAIL";
