export const GET_DATA_SUCCESS = "profile/GET_SUCCESS";
export const GET_DATA_FAIL = "profile/GET_FAIL";
export const GET_DATA_REQUEST = "profile/GET_REQUEST";
export const GET_PHONE_VALIDATION = "profile/GET_PHONE_VALIDATION";
export const GET_IDENFICATION_VALIDATION = "profile/GET_IDENFICATION_VALIDATION";
export const GET_EWALLET_VALIDATION = "profile/GET_EWALLET_VALIDATION";


