name: CI

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:

      - name: CD - Pull source code
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: cd /home/ubuntu/webapp && git fetch origin main && git reset --hard origin/main && git pull
      - name: CD - Stop existing server-master's container and remove container
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: sudo docker stop web-app-master && sudo docker rm stop web-app-master && sudo docker images -a | sudo grep "swg/web-app-master" | sudo awk '{print $3}' | sudo xargs docker rmi
      - name: CD - Build Docker image
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: cd /home/ubuntu/webapp && sudo docker build . -t swg/web-app-master
      - name: CD - Start Express container
        uses: appleboy/ssh-action@master
        with:
          host: 13.215.133.39
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: sudo docker run --name="web-app-master" -p 3000:3000 -d swg/web-app-master
